# Generated by Django 2.0.2 on 2018-07-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Step1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Beregning1',
        ),
    ]
